### ISSUE TITLE
Deye Hybrid sensors unavailable in 24.09.22

### ISSUE THREAD

**Issue by terzo33** [davidrapan/ha-solarman#170] opened 2024-09-22 19:19 UTC
Hi @davidrapan , after update to 24.09.22 i have some sensors unavailable

![Screenshot_20240922_211715_Home Assistant.jpg](https://github.com/user-attachments/assets/bad00c70-72ff-437d-8bb2-81028b056c2a)

![Screenshot_20240922_211719_Home Assistant.jpg](https://github.com/user-attachments/assets/0f45c14f-a005-47ca-b57c-1562f44d341e)

![Screenshot_20240922_211723_Home Assistant.jpg](https://github.com/user-attachments/assets/2ad841e5-3226-47cf-9a3c-688b17e4e1b4)

![Screenshot_20240922_211729_Home Assistant.jpg](https://github.com/user-attachments/assets/2a8b6411-3b96-487e-825c-5b2ad8b4e98d)

![Screenshot_20240922_212016_Home Assistant.jpg](https://github.com/user-attachments/assets/d98fecaf-196c-4bae-836b-756ef9cac85d)

**Comment by davidrapan** [comment] 2024-09-22 19:31
Yes, that's not a bug. I refactored entity names which did not fit our (soon to be) standardized scheme. And some static values (like serial number) were transferred into attributes to **Device State** entity.

**Comment by terzo33** [comment] 2024-09-22 19:36
Awesome. Thanks

**Closed** 2024-09-22 19:36 UTC

**Comment by terzo33** [comment] 2024-09-22 19:40
Little OT: hacs does not see updates to your integration. I have to download it manually everytime. Why?

**Comment by davidrapan** [comment] 2024-09-22 19:49
Not sure about that but I somehow noticed that too after HACS 2.0 was release. Maybe it just takes longer before it checks if there is anything to update?

**But it does notice the update when you click on the Update information under 3 dots menu.**

**Comment by terzo33** [comment] 2024-09-22 19:54
> Not sure about that but I somehow noticed that too after HACS 2.0 was released. Maybe it just takes longer before it checks if there is anything to update?
> 
> **But it does notice the update when you click on the Update information under 3 dots menu.**

when i press on the 3 dots nothing happens. i was stuck on version 24.09.08 after about 10 days i accidentally saw that version 24.09.18 was available. no update notification

**Comment by davidrapan** [comment] 2024-09-22 19:59
And did you click there on **Update information**?

**Comment by terzo33** [comment] 2024-09-22 20:04
> And did you click there on **Update information**?

Yes, nothing happened

**Comment by davidrapan** [comment] 2024-09-22 20:50
Weird, it did works that way for me.
