### ISSUE TITLE
Production Values & Alert Entities not working anymore

### ISSUE THREAD

**Issue by aViN-187** [davidrapan/ha-solarman#76] opened 2024-08-11 20:09 UTC
Hi there,

i'm kind of new to home-assistant therefore please be kind to me. After the Update Update of 2024.8 (at least that is my assumption) I'm got the following issues:

Value of my 2MTTP Deye in total comsumption does not match. 

in the past i always got values between 2-5 kwh. A typical day looks like this: 
![image](https://github.com/user-attachments/assets/01b19ea4-0f00-42f8-b059-b917c8c10d4d)
After the update it looks like this:
![image](https://github.com/user-attachments/assets/ca58333a-115a-463b-8db2-16828cfd0465)
Values add 200 kwh to a day ... same goes on the next days:
![image](https://github.com/user-attachments/assets/73ee2c49-9cac-41cb-ae82-e0337c893e0f)

Value=sensor.deye_total_production
![image](https://github.com/user-attachments/assets/498460f3-077f-4f16-8050-17aa58194a6f)

2nd Issue: 
The Value: Altert on the Deye Decvice - every 5 secounds the value chances. In my mind i can't remember this behaviour. When i check the micro inverter manually via the ip/statuspage - all looks good. 

![image](https://github.com/user-attachments/assets/265a289f-8308-41f7-a612-1237920a6d5c)

Maybe someone could help me out - thanks

**Comment by davidrapan** [comment] 2024-08-11 20:24
Hi @aViN-187, I think it's proly the same as https://github.com/davidrapan/ha-solarman/issues/65. I made the fix in: [fix: Deye microinverters PV validation to 0.1](https://github.com/davidrapan/ha-solarman/commit/6ea759340755d80be6f96aadeaf39c509a3236e6). And it's already part of pre-release v24.08.10 but you will have to enable beta versions in the HACS under redownload button in the right top corner to see beta (pre-release) versions.

**Comment by davidrapan** [comment] 2024-08-11 20:28
Duplicate of https://github.com/davidrapan/ha-solarman/issues/65

**Comment by aViN-187** [comment] 2024-08-11 20:38
thanks for the quick reply - i activated beta and did the installation. I will report tomorrow. I assume the "wrong" values from the past days will not be corrected by the dashboard?

**Comment by davidrapan** [comment] 2024-08-11 20:53
Sadly no :-/ But you can at least maybe clear them using Developer tools and then STATISTICS page. You can find the Total Production sensor and adjust the data.

**Comment by aViN-187** [comment] 2024-08-12 09:03
Issue resolved: 

Data is looking good so far - thanks! 
![image](https://github.com/user-attachments/assets/9082424a-09f4-4084-8374-f30aa3ead47e)


nethertheless Alert Issue is still the same - what can i do to help out?
![image](https://github.com/user-attachments/assets/c9fb2da0-5acb-4803-bd8e-aada86b94067)

**Comment by davidrapan** [comment] 2024-08-12 09:10
I'm glad to hear that!

> Alert Issue is still the same - what can i do to help out?

I'll look into it and let you know. 😉

**Comment by davidrapan** [comment] 2024-08-12 09:26
@CrazyUs3r? You were doing the changes there. Could you maybe elaborate? Thanks.

**Comment by CrazyUs3r** [comment] 2024-08-12 09:43
@aViN-187 Which inverter do you use with which firmware

**Comment by aViN-187** [comment] 2024-08-12 10:50
hey @CrazyUs3r 

Modell: deye sun800g3
![image](https://github.com/user-attachments/assets/443e5e1c-14fb-4925-a410-39753e01f93b)

The behavior startet 6. August. Before that no changes on the Alert.

![image](https://github.com/user-attachments/assets/5640cb96-2a30-458d-9e63-73c31807c5f9)
After that - see post above

**Comment by davidrapan** [comment] 2024-08-12 13:01
Try definition profile from this commit: [feat: Updated Deye 2MPPT and 4MPPT](https://github.com/davidrapan/ha-solarman/commit/6f9e9e70d39aacee83a8b8297a40c43f19896d4a)

**Comment by CrazyUs3r** [comment] 2024-08-12 15:13
@davidrapan with mod protocol are you using?

**Comment by aViN-187** [comment] 2024-08-12 17:04
> Try definition profile from this commit: [feat: Updated Deye 2MPPT and 4MPPT](https://github.com/davidrapan/ha-solarman/commit/6f9e9e70d39aacee83a8b8297a40c43f19896d4a)

Not working at all - 9 Duplicate Keys, etc. ... at least for the 2MPPT Version

**Comment by davidrapan** [comment] 2024-08-12 18:42
Oh did I f*cked up something?

**Comment by CrazyUs3r** [comment] 2024-08-12 18:52
i I'll try tomorrow morning since I don't have any sun anymore

**Comment by davidrapan** [comment] 2024-08-12 19:58
Yeah well and be aware that this version already did go trough naming standardization and for example Daily Production sensors changed into Today Production, etc. So migrate your history if you need that under new name using step by step guide from wiki. (But that sensor is not that important anyway as all the data are already in the Total version of that sensor but letting you know so you are not surprised) 😉

**Comment by aViN-187** [comment] 2024-08-13 15:18
Update:

Total Production looks strange ... i got values in the statistics, but not in the energy overview. 

![image](https://github.com/user-attachments/assets/daca698f-676b-4e1c-b107-ac2890a41f38)

![image](https://github.com/user-attachments/assets/ae3bbbc8-4427-4267-a611-df469a05c608)

Alert Management looks fixed - since i restartet HA with the new 2MPPT file - all goods, thanks!

![image](https://github.com/user-attachments/assets/5bf75edf-9395-4ebb-8870-55969fb5cf16)

**Comment by davidrapan** [comment] 2024-08-13 15:55
Look at the entity id of that sensor, didn't it got messed up somehow?

**Comment by CrazyUs3r** [comment] 2024-08-13 16:00
I have no Problem. I night is all offline but total go normal up without 0


![Screenshot_20240813_175752_Home Assistant](https://github.com/user-attachments/assets/1bc962f3-b0b8-4761-a41c-65216c5ce413)
![Screenshot_20240813_175832_Home Assistant](https://github.com/user-attachments/assets/60c7ac0e-f1e9-44b4-a073-3928382369f7)

**Comment by CrazyUs3r** [comment] 2024-08-13 16:01
Load the firmware 32-D1 again up in inverter

**Comment by davidrapan** [comment] 2024-08-13 16:27
@CrazyUs3r, great!

@aViN-187,
> Alert Management looks fixed - since i restartet HA with the new 2MPPT file - all goods, thanks!

Does the "Value" in attributes changes? If so does it appear simply random or some specific values? If so, what values?

**Comment by CrazyUs3r** [comment] 2024-08-13 16:58
and my device status = fault is a problem from the ac wire this i check at the weekend

**Comment by aViN-187** [comment] 2024-08-13 18:51
in the meantime values did appear .. so i assume all good for now.
![image](https://github.com/user-attachments/assets/671168fe-ef1a-40b6-817f-edd88e23e472)

in regards to the error message - not value at all, but now since no sun in shining the state changes to error. 
![image](https://github.com/user-attachments/assets/9581e4e2-8a9d-45f5-8c4c-5e678424f265)

I assume that behaviour correct? :) Nethertheless big thanks for your work

**Comment by davidrapan** [comment] 2024-08-13 21:40
@aViN-187 That's awesome and you are very welcome! 🥂

Anyway, still suggest you to delete and re-add your device to clear out those nonexistent sensors. 😉

**Closed by davidrapan** 2024-08-13 21:40 UTC
Labels: bug, duplicate
