### ISSUE TITLE
Control the inverter

### ISSUE THREAD

**Issue by Vollpanto** [davidrapan/ha-solarman#16] opened 2024-07-10 12:59 UTC
Hi,
thank you for your great work.
Is it also possible to do some kind of Controlling the inverter?
e.g. Charge the battery with grid power?

Thanks.

**Comment by davidrapan** [comment] 2024-07-10 13:11
Duplicate of #9

**Comment by Vollpanto** [comment] 2024-07-10 13:13
Oh, thanks. I missed that.

Can't wait for the next update.
👯

**Closed** 2024-07-10 13:14 UTC
Labels: duplicate
